### ISSUE TITLE
software license?

### ISSUE THREAD

**Issue by tisdall** [maisano/pyramid_cachebust#4]
Have you considered releasing this under the MIT licence so it can be included in other works?

**Comment by farvour** [comment]
Seconded.  MIT or BSD recommendation for me.  MIT is simpler, however.

**Comment by maisano** [comment]
yea, i had always considered releasing it under the MIT license.

**Comment by maisano** [comment]
feel free to submit a pull request adding the MIT license–i would add it myself, though i am currently without a computer.

**Comment by tisdall** [comment]
k
